# Generated by Django 5.2.3 on 2025-07-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_task_due_date_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='designation',
        ),
    ]
