# Generated by Django 5.1.6 on 2025-07-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_taskupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
