# Generated by Django 5.1.6 on 2025-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_project_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Python Developer', 'Python Developer'), ('Data Scientist', 'Data Scientist'), ('Sr. Data Scientist', 'Sr. Data Scientist'), ('Team Lead', 'Team Lead'), ('Full Stack Developer', 'Full Stack Developer')], max_length=50),
        ),
    ]
